"""updated tables

Revision ID: 71a3148a7507
Revises: d1fac7c8e664
Create Date: 2023-09-21 00:27:49.283465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a3148a7507'
down_revision = 'd1fac7c8e664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
